name: Deploy Ghost Theme

on:
  push:
    tags:
      - 'v*.*.*'  # This will trigger the workflow for tags like v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install jsonwebtoken axios form-data

      - name: Zip theme directory
        run: |
          THEME_DIR="/"
          THEME_ZIP="theme.zip"
          cd $THEME_DIR
          zip -r ../$THEME_ZIP ./*
        shell: bash

      - name: Deploy theme
        env:
          GHOST_ADMIN_API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
          GHOST_ADMIN_API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
          THEME_PATH: ${{ github.workspace }}/theme.zip
        run: node deployTheme.js
